using System.Collections;
using System.Collections.Generic;
using UnityEngine;

[System.Serializable]
public class EnemyTranslationTableEntry
{
    public string EnemyName;
    public int EnemyHealth;
    public enum EnemyType { Nothing, Fiend, FiendNest, Breakable };
    public EnemyType Type;
    
    public enum ItemsDropped { Snowcube, Bone, Eyeball, Meat, Tail, Coins };
    public List<ItemsDropped> itemDroppedList;
    
    public EnemyTranslationTableEntry( string enemyName , int health)
    {
        this.EnemyName = enemyName;
        this.EnemyHealth = health;
    }



}
[CreateAssetMenu(menuName = "RPG/Enemy Table", fileName = "EnemyTranslation_Table")]
public class EnemyTranslation_Table : BaseEnemyTranslation
{
    [SerializeField] List<EnemyTranslationTableEntry> Table;

    public override int TakeDamage(string enemyName, int damage, string enemyTag)
    {

        foreach (EnemyTranslationTableEntry tableEntry in Table)
        {
            if (enemyTag == tableEntry.EnemyName)
            {
                EnemyTranslationTableEntry enemy01 = new EnemyTranslationTableEntry(tableEntry.EnemyName, tableEntry.EnemyHealth);
                Debug.Log("This is the item's health before deduction " + enemy01.EnemyHealth);
                enemy01.EnemyHealth -= damage;
                Debug.Log("This is the item's health after deduction " + enemy01.EnemyHealth);
                //when the player hits, create a class for it with name, health, and deduct the health by 1 per second by a cooldown timing generated by the players attack, add it to a list of classes
                //ItemHealth = tableEntry.health - damage;

                Debug.Log(EnemyHealth);
                return EnemyHealth;
                //returns the health of that item


            }



        }


        //if the collision.tag == name of the Item (Write for loop to find)
        //if XP points >0 , add points to the player
        throw new System.NotImplementedException();

    }

    public override string DropItem(List<ItemsDropped> itemDroppedList)
    {

        foreach (EnemyTranslationTableEntry tableEntry in Table)
        {
           
              //for the length of the list, choose a random number and make that

          



        }


        //if the collision.tag == name of the Item (Write for loop to find)
        //if XP points >0 , add points to the player
        throw new System.NotImplementedException();

    }


}